<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>Lib.test.test_syntax : API documentation</title>

    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="apidocs.css" />
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="index.html">
            Python3.8 API Documentation
          </a>
        </div>
      </div>
    </nav>

    <div id="showPrivate">
      <button class="btn btn-link" onclick="togglePrivate()">Toggle Private API</button>
    </div>

    <div class="container">

      <div class="page-header">
        <h1 class="module"><code><a href="Lib.html" class="code" data-type="Package">Lib</a>.<a href="Lib.test.html" class="code" data-type="Package">test</a>.<a href="Lib.test.test_syntax.html" class="code" data-type="Module">test_syntax</a></code></h1>
      </div>

      <div class="categoryHeader">
        module documentation
      </div>

      <div class="extrasDocstring">
        
        <p></p>
      </div>

      <div class="moduleDocstring">
        <div><p class="pre">This module tests SyntaxErrors.

Here's an example of the sort of thing that is tested.

&gt;&gt;&gt; def f(x):
...     global x
Traceback (most recent call last):
SyntaxError: name 'x' is parameter and global

The tests are all raise SyntaxErrors.  They were created by checking
each C call that raises SyntaxError.  There are several modules that
raise these exceptions-- ast.c, compile.c, future.c, pythonrun.c, and
symtable.c.

The parser itself outlaws a lot of invalid syntax.  None of these
errors are tested here at the moment.  We should add some tests; since
there are infinitely many programs with invalid syntax, we would need
to be judicious in selecting some.

The compiler generates a synthetic module name for code executed by
doctest.  Since all the code comes from the same module, a suffix like
[1] is appended to the module name, As a consequence, changing the
order of tests in this module means renumbering all the errors after
it.  (Maybe we should enable the ellipsis option for these tests.)

In ast.c, syntax errors are raised by calling ast_error().

Errors from set_context():

&gt;&gt;&gt; obj.None = 1
Traceback (most recent call last):
SyntaxError: invalid syntax

&gt;&gt;&gt; None = 1
Traceback (most recent call last):
SyntaxError: cannot assign to None

&gt;&gt;&gt; obj.True = 1
Traceback (most recent call last):
SyntaxError: invalid syntax

&gt;&gt;&gt; True = 1
Traceback (most recent call last):
SyntaxError: cannot assign to True

&gt;&gt;&gt; (True := 1)
Traceback (most recent call last):
SyntaxError: cannot use assignment expressions with True

&gt;&gt;&gt; obj.__debug__ = 1
Traceback (most recent call last):
SyntaxError: cannot assign to __debug__

&gt;&gt;&gt; __debug__ = 1
Traceback (most recent call last):
SyntaxError: cannot assign to __debug__

&gt;&gt;&gt; (__debug__ := 1)
Traceback (most recent call last):
SyntaxError: cannot assign to __debug__

&gt;&gt;&gt; f() = 1
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; yield = 1
Traceback (most recent call last):
SyntaxError: assignment to yield expression not possible

&gt;&gt;&gt; del f()
Traceback (most recent call last):
SyntaxError: cannot delete function call

&gt;&gt;&gt; a + 1 = 2
Traceback (most recent call last):
SyntaxError: cannot assign to operator

&gt;&gt;&gt; (x for x in x) = 1
Traceback (most recent call last):
SyntaxError: cannot assign to generator expression

&gt;&gt;&gt; 1 = 1
Traceback (most recent call last):
SyntaxError: cannot assign to literal

&gt;&gt;&gt; "abc" = 1
Traceback (most recent call last):
SyntaxError: cannot assign to literal

&gt;&gt;&gt; b"" = 1
Traceback (most recent call last):
SyntaxError: cannot assign to literal

&gt;&gt;&gt; ... = 1
Traceback (most recent call last):
SyntaxError: cannot assign to Ellipsis

&gt;&gt;&gt; `1` = 1
Traceback (most recent call last):
SyntaxError: invalid syntax

If the left-hand side of an assignment is a list or tuple, an illegal
expression inside that contain should still cause a syntax error.
This test just checks a couple of cases rather than enumerating all of
them.

&gt;&gt;&gt; (a, "b", c) = (1, 2, 3)
Traceback (most recent call last):
SyntaxError: cannot assign to literal

&gt;&gt;&gt; (a, True, c) = (1, 2, 3)
Traceback (most recent call last):
SyntaxError: cannot assign to True

&gt;&gt;&gt; (a, __debug__, c) = (1, 2, 3)
Traceback (most recent call last):
SyntaxError: cannot assign to __debug__

&gt;&gt;&gt; (a, *True, c) = (1, 2, 3)
Traceback (most recent call last):
SyntaxError: cannot assign to True

&gt;&gt;&gt; (a, *__debug__, c) = (1, 2, 3)
Traceback (most recent call last):
SyntaxError: cannot assign to __debug__

&gt;&gt;&gt; [a, b, c + 1] = [1, 2, 3]
Traceback (most recent call last):
SyntaxError: cannot assign to operator

&gt;&gt;&gt; [a, b[1], c + 1] = [1, 2, 3]
Traceback (most recent call last):
SyntaxError: cannot assign to operator

&gt;&gt;&gt; [a, b.c.d, c + 1] = [1, 2, 3]
Traceback (most recent call last):
SyntaxError: cannot assign to operator

&gt;&gt;&gt; a if 1 else b = 1
Traceback (most recent call last):
SyntaxError: cannot assign to conditional expression

&gt;&gt;&gt; True = True = 3
Traceback (most recent call last):
SyntaxError: cannot assign to True

&gt;&gt;&gt; x = y = True = z = 3
Traceback (most recent call last):
SyntaxError: cannot assign to True

&gt;&gt;&gt; x = y = yield = 1
Traceback (most recent call last):
SyntaxError: assignment to yield expression not possible

&gt;&gt;&gt; a, b += 1, 2
Traceback (most recent call last):
SyntaxError: 'tuple' is an illegal expression for augmented assignment

&gt;&gt;&gt; (a, b) += 1, 2
Traceback (most recent call last):
SyntaxError: 'tuple' is an illegal expression for augmented assignment

&gt;&gt;&gt; [a, b] += 1, 2
Traceback (most recent call last):
SyntaxError: 'list' is an illegal expression for augmented assignment

Invalid targets in `for` loops and `with` statements should also
produce a specialized error message

&gt;&gt;&gt; for a() in b: pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; for (a, b()) in b: pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; for [a, b()] in b: pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; for (*a, b, c+1) in b: pass
Traceback (most recent call last):
SyntaxError: cannot assign to operator

&gt;&gt;&gt; for (x, *(y, z.d())) in b: pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; for a, b() in c: pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; for a, b, (c + 1, d()): pass
Traceback (most recent call last):
SyntaxError: cannot assign to operator

&gt;&gt;&gt; for i &lt; (): pass
Traceback (most recent call last):
SyntaxError: invalid syntax

&gt;&gt;&gt; for a, b
Traceback (most recent call last):
SyntaxError: invalid syntax

&gt;&gt;&gt; with a as b(): pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; with a as (b, c()): pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; with a as [b, c()]: pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; with a as (*b, c, d+1): pass
Traceback (most recent call last):
SyntaxError: cannot assign to operator

&gt;&gt;&gt; with a as (x, *(y, z.d())): pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; with a as b, c as d(): pass
Traceback (most recent call last):
SyntaxError: cannot assign to function call

&gt;&gt;&gt; with a as b
Traceback (most recent call last):
SyntaxError: invalid syntax

&gt;&gt;&gt; p = p =
Traceback (most recent call last):
SyntaxError: invalid syntax

From compiler_complex_args():

&gt;&gt;&gt; def f(None=1):
...     pass
Traceback (most recent call last):
SyntaxError: invalid syntax

From ast_for_arguments():

&gt;&gt;&gt; def f(x, y=1, z):
...     pass
Traceback (most recent call last):
SyntaxError: non-default argument follows default argument

&gt;&gt;&gt; def f(x, None):
...     pass
Traceback (most recent call last):
SyntaxError: invalid syntax

&gt;&gt;&gt; def f(*None):
...     pass
Traceback (most recent call last):
SyntaxError: invalid syntax

&gt;&gt;&gt; def f(**None):
...     pass
Traceback (most recent call last):
SyntaxError: invalid syntax

&gt;&gt;&gt; import ast; ast.parse('''
... def f(
...     *, # type: int
...     a, # type: int
... ):
...     pass
... ''', type_comments=True)
Traceback (most recent call last):
SyntaxError: bare * has associated type comment


From ast_for_funcdef():

&gt;&gt;&gt; def None(x):
...     pass
Traceback (most recent call last):
SyntaxError: invalid syntax


From ast_for_call():

&gt;&gt;&gt; def f(it, *varargs, **kwargs):
...     return list(it)
&gt;&gt;&gt; L = range(10)
&gt;&gt;&gt; f(x for x in L)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
&gt;&gt;&gt; f(x for x in L, 1)
Traceback (most recent call last):
SyntaxError: Generator expression must be parenthesized
&gt;&gt;&gt; f(x for x in L, y=1)
Traceback (most recent call last):
SyntaxError: Generator expression must be parenthesized
&gt;&gt;&gt; f(x for x in L, *[])
Traceback (most recent call last):
SyntaxError: Generator expression must be parenthesized
&gt;&gt;&gt; f(x for x in L, **{})
Traceback (most recent call last):
SyntaxError: Generator expression must be parenthesized
&gt;&gt;&gt; f(L, x for x in L)
Traceback (most recent call last):
SyntaxError: Generator expression must be parenthesized
&gt;&gt;&gt; f(x for x in L, y for y in L)
Traceback (most recent call last):
SyntaxError: Generator expression must be parenthesized
&gt;&gt;&gt; f(x for x in L,)
Traceback (most recent call last):
SyntaxError: Generator expression must be parenthesized
&gt;&gt;&gt; f((x for x in L), 1)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
&gt;&gt;&gt; class C(x for x in L):
...     pass
Traceback (most recent call last):
SyntaxError: invalid syntax

&gt;&gt;&gt; def g(*args, **kwargs):
...     print(args, sorted(kwargs.items()))
&gt;&gt;&gt; g(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
...   20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
...   38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
...   56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
...   74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
...   92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
...   108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
...   122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
...   136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
...   150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
...   164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
...   178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
...   192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
...   206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,
...   220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
...   234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
...   248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261,
...   262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275,
...   276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289,
...   290, 291, 292, 293, 294, 295, 296, 297, 298, 299)  # doctest: +ELLIPSIS
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ..., 297, 298, 299) []

&gt;&gt;&gt; g(a000=0, a001=1, a002=2, a003=3, a004=4, a005=5, a006=6, a007=7, a008=8,
...   a009=9, a010=10, a011=11, a012=12, a013=13, a014=14, a015=15, a016=16,
...   a017=17, a018=18, a019=19, a020=20, a021=21, a022=22, a023=23, a024=24,
...   a025=25, a026=26, a027=27, a028=28, a029=29, a030=30, a031=31, a032=32,
...   a033=33, a034=34, a035=35, a036=36, a037=37, a038=38, a039=39, a040=40,
...   a041=41, a042=42, a043=43, a044=44, a045=45, a046=46, a047=47, a048=48,
...   a049=49, a050=50, a051=51, a052=52, a053=53, a054=54, a055=55, a056=56,
...   a057=57, a058=58, a059=59, a060=60, a061=61, a062=62, a063=63, a064=64,
...   a065=65, a066=66, a067=67, a068=68, a069=69, a070=70, a071=71, a072=72,
...   a073=73, a074=74, a075=75, a076=76, a077=77, a078=78, a079=79, a080=80,
...   a081=81, a082=82, a083=83, a084=84, a085=85, a086=86, a087=87, a088=88,
...   a089=89, a090=90, a091=91, a092=92, a093=93, a094=94, a095=95, a096=96,
...   a097=97, a098=98, a099=99, a100=100, a101=101, a102=102, a103=103,
...   a104=104, a105=105, a106=106, a107=107, a108=108, a109=109, a110=110,
...   a111=111, a112=112, a113=113, a114=114, a115=115, a116=116, a117=117,
...   a118=118, a119=119, a120=120, a121=121, a122=122, a123=123, a124=124,
...   a125=125, a126=126, a127=127, a128=128, a129=129, a130=130, a131=131,
...   a132=132, a133=133, a134=134, a135=135, a136=136, a137=137, a138=138,
...   a139=139, a140=140, a141=141, a142=142, a143=143, a144=144, a145=145,
...   a146=146, a147=147, a148=148, a149=149, a150=150, a151=151, a152=152,
...   a153=153, a154=154, a155=155, a156=156, a157=157, a158=158, a159=159,
...   a160=160, a161=161, a162=162, a163=163, a164=164, a165=165, a166=166,
...   a167=167, a168=168, a169=169, a170=170, a171=171, a172=172, a173=173,
...   a174=174, a175=175, a176=176, a177=177, a178=178, a179=179, a180=180,
...   a181=181, a182=182, a183=183, a184=184, a185=185, a186=186, a187=187,
...   a188=188, a189=189, a190=190, a191=191, a192=192, a193=193, a194=194,
...   a195=195, a196=196, a197=197, a198=198, a199=199, a200=200, a201=201,
...   a202=202, a203=203, a204=204, a205=205, a206=206, a207=207, a208=208,
...   a209=209, a210=210, a211=211, a212=212, a213=213, a214=214, a215=215,
...   a216=216, a217=217, a218=218, a219=219, a220=220, a221=221, a222=222,
...   a223=223, a224=224, a225=225, a226=226, a227=227, a228=228, a229=229,
...   a230=230, a231=231, a232=232, a233=233, a234=234, a235=235, a236=236,
...   a237=237, a238=238, a239=239, a240=240, a241=241, a242=242, a243=243,
...   a244=244, a245=245, a246=246, a247=247, a248=248, a249=249, a250=250,
...   a251=251, a252=252, a253=253, a254=254, a255=255, a256=256, a257=257,
...   a258=258, a259=259, a260=260, a261=261, a262=262, a263=263, a264=264,
...   a265=265, a266=266, a267=267, a268=268, a269=269, a270=270, a271=271,
...   a272=272, a273=273, a274=274, a275=275, a276=276, a277=277, a278=278,
...   a279=279, a280=280, a281=281, a282=282, a283=283, a284=284, a285=285,
...   a286=286, a287=287, a288=288, a289=289, a290=290, a291=291, a292=292,
...   a293=293, a294=294, a295=295, a296=296, a297=297, a298=298, a299=299)
...  # doctest: +ELLIPSIS
() [('a000', 0), ('a001', 1), ('a002', 2), ..., ('a298', 298), ('a299', 299)]

&gt;&gt;&gt; class C:
...     def meth(self, *args):
...         return args
&gt;&gt;&gt; obj = C()
&gt;&gt;&gt; obj.meth(
...   0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
...   20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
...   38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
...   56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
...   74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
...   92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107,
...   108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
...   122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
...   136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
...   150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
...   164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
...   178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
...   192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
...   206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,
...   220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
...   234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
...   248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261,
...   262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275,
...   276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289,
...   290, 291, 292, 293, 294, 295, 296, 297, 298, 299)  # doctest: +ELLIPSIS
(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ..., 297, 298, 299)

# &gt;&gt;&gt; f(lambda x: x[0] = 3)
# Traceback (most recent call last):
# SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

The grammar accepts any test (basically, any expression) in the
keyword slot of a call site.  Test a few different options.

# &gt;&gt;&gt; f(x()=2)
# Traceback (most recent call last):
# SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
# &gt;&gt;&gt; f(a or b=1)
# Traceback (most recent call last):
# SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
# &gt;&gt;&gt; f(x.y=1)
# Traceback (most recent call last):
# SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
# &gt;&gt;&gt; f((x)=2)
# Traceback (most recent call last):
# SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
# &gt;&gt;&gt; f(True=2)
# Traceback (most recent call last):
# SyntaxError: cannot assign to True
&gt;&gt;&gt; f(__debug__=1)
Traceback (most recent call last):
SyntaxError: cannot assign to __debug__
&gt;&gt;&gt; __debug__: int
Traceback (most recent call last):
SyntaxError: cannot assign to __debug__


More set_context():

&gt;&gt;&gt; (x for x in x) += 1
Traceback (most recent call last):
SyntaxError: 'generator expression' is an illegal expression for augmented assignment
&gt;&gt;&gt; None += 1
Traceback (most recent call last):
SyntaxError: 'None' is an illegal expression for augmented assignment
&gt;&gt;&gt; __debug__ += 1
Traceback (most recent call last):
SyntaxError: cannot assign to __debug__
&gt;&gt;&gt; f() += 1
Traceback (most recent call last):
SyntaxError: 'function call' is an illegal expression for augmented assignment


Test continue in finally in weird combinations.

continue in for loop under finally should be ok.

    &gt;&gt;&gt; def test():
    ...     try:
    ...         pass
    ...     finally:
    ...         for abc in range(10):
    ...             continue
    ...     print(abc)
    &gt;&gt;&gt; test()
    9

continue in a finally should be ok.

    &gt;&gt;&gt; def test():
    ...    for abc in range(10):
    ...        try:
    ...            pass
    ...        finally:
    ...            continue
    ...    print(abc)
    &gt;&gt;&gt; test()
    9

    &gt;&gt;&gt; def test():
    ...    for abc in range(10):
    ...        try:
    ...            pass
    ...        finally:
    ...            try:
    ...                continue
    ...            except:
    ...                pass
    ...    print(abc)
    &gt;&gt;&gt; test()
    9

    &gt;&gt;&gt; def test():
    ...    for abc in range(10):
    ...        try:
    ...            pass
    ...        finally:
    ...            try:
    ...                pass
    ...            except:
    ...                continue
    ...    print(abc)
    &gt;&gt;&gt; test()
    9

A continue outside loop should not be allowed.

    &gt;&gt;&gt; def foo():
    ...     try:
    ...         pass
    ...     finally:
    ...         continue
    Traceback (most recent call last):
      ...
    SyntaxError: 'continue' not properly in loop

There is one test for a break that is not in a loop.  The compiler
uses a single data structure to keep track of try-finally and loops,
so we need to be sure that a break is actually inside a loop.  If it
isn't, there should be a syntax error.

   &gt;&gt;&gt; try:
   ...     print(1)
   ...     break
   ...     print(2)
   ... finally:
   ...     print(3)
   Traceback (most recent call last):
     ...
   SyntaxError: 'break' outside loop

This raises a SyntaxError, it used to raise a SystemError.
Context for this change can be found on issue #27514

In 2.5 there was a missing exception and an assert was triggered in a debug
build.  The number of blocks must be greater than CO_MAXBLOCKS.  SF #1565514

   &gt;&gt;&gt; while 1:
   ...  while 2:
   ...   while 3:
   ...    while 4:
   ...     while 5:
   ...      while 6:
   ...       while 8:
   ...        while 9:
   ...         while 10:
   ...          while 11:
   ...           while 12:
   ...            while 13:
   ...             while 14:
   ...              while 15:
   ...               while 16:
   ...                while 17:
   ...                 while 18:
   ...                  while 19:
   ...                   while 20:
   ...                    while 21:
   ...                     while 22:
   ...                      break
   Traceback (most recent call last):
     ...
   SyntaxError: too many statically nested blocks

Misuse of the nonlocal and global statement can lead to a few unique syntax errors.

   &gt;&gt;&gt; def f():
   ...     print(x)
   ...     global x
   Traceback (most recent call last):
     ...
   SyntaxError: name 'x' is used prior to global declaration

   &gt;&gt;&gt; def f():
   ...     x = 1
   ...     global x
   Traceback (most recent call last):
     ...
   SyntaxError: name 'x' is assigned to before global declaration

   &gt;&gt;&gt; def f(x):
   ...     global x
   Traceback (most recent call last):
     ...
   SyntaxError: name 'x' is parameter and global

   &gt;&gt;&gt; def f():
   ...     x = 1
   ...     def g():
   ...         print(x)
   ...         nonlocal x
   Traceback (most recent call last):
     ...
   SyntaxError: name 'x' is used prior to nonlocal declaration

   &gt;&gt;&gt; def f():
   ...     x = 1
   ...     def g():
   ...         x = 2
   ...         nonlocal x
   Traceback (most recent call last):
     ...
   SyntaxError: name 'x' is assigned to before nonlocal declaration

   &gt;&gt;&gt; def f(x):
   ...     nonlocal x
   Traceback (most recent call last):
     ...
   SyntaxError: name 'x' is parameter and nonlocal

   &gt;&gt;&gt; def f():
   ...     global x
   ...     nonlocal x
   Traceback (most recent call last):
     ...
   SyntaxError: name 'x' is nonlocal and global

   &gt;&gt;&gt; def f():
   ...     nonlocal x
   Traceback (most recent call last):
     ...
   SyntaxError: no binding for nonlocal 'x' found

From SF bug #1705365
   &gt;&gt;&gt; nonlocal x
   Traceback (most recent call last):
     ...
   SyntaxError: nonlocal declaration not allowed at module level

From https://bugs.python.org/issue25973
   &gt;&gt;&gt; class A:
   ...     def f(self):
   ...         nonlocal __x
   Traceback (most recent call last):
     ...
   SyntaxError: no binding for nonlocal '_A__x' found


This tests assignment-context; there was a bug in Python 2.5 where compiling
a complex 'if' (one with 'elif') would fail to notice an invalid suite,
leading to spurious errors.

   &gt;&gt;&gt; if 1:
   ...   x() = 1
   ... elif 1:
   ...   pass
   Traceback (most recent call last):
     ...
   SyntaxError: cannot assign to function call

   &gt;&gt;&gt; if 1:
   ...   pass
   ... elif 1:
   ...   x() = 1
   Traceback (most recent call last):
     ...
   SyntaxError: cannot assign to function call

   &gt;&gt;&gt; if 1:
   ...   x() = 1
   ... elif 1:
   ...   pass
   ... else:
   ...   pass
   Traceback (most recent call last):
     ...
   SyntaxError: cannot assign to function call

   &gt;&gt;&gt; if 1:
   ...   pass
   ... elif 1:
   ...   x() = 1
   ... else:
   ...   pass
   Traceback (most recent call last):
     ...
   SyntaxError: cannot assign to function call

   &gt;&gt;&gt; if 1:
   ...   pass
   ... elif 1:
   ...   pass
   ... else:
   ...   x() = 1
   Traceback (most recent call last):
     ...
   SyntaxError: cannot assign to function call

Make sure that the old "raise X, Y[, Z]" form is gone:
   &gt;&gt;&gt; raise X, Y
   Traceback (most recent call last):
     ...
   SyntaxError: invalid syntax
   &gt;&gt;&gt; raise X, Y, Z
   Traceback (most recent call last):
     ...
   SyntaxError: invalid syntax


&gt;&gt;&gt; f(a=23, a=234)
Traceback (most recent call last):
   ...
SyntaxError: keyword argument repeated: a

&gt;&gt;&gt; {1, 2, 3} = 42
Traceback (most recent call last):
SyntaxError: cannot assign to set display

&gt;&gt;&gt; {1: 2, 3: 4} = 42
Traceback (most recent call last):
SyntaxError: cannot assign to dict display

&gt;&gt;&gt; f'{x}' = 42
Traceback (most recent call last):
SyntaxError: cannot assign to f-string expression

&gt;&gt;&gt; f'{x}-{y}' = 42
Traceback (most recent call last):
SyntaxError: cannot assign to f-string expression

&gt;&gt;&gt; from t import x,
Traceback (most recent call last):
SyntaxError: trailing comma not allowed without surrounding parentheses

&gt;&gt;&gt; from t import x,y,
Traceback (most recent call last):
SyntaxError: trailing comma not allowed without surrounding parentheses

&gt;&gt;&gt; (): int
Traceback (most recent call last):
SyntaxError: only single target (not tuple) can be annotated
&gt;&gt;&gt; []: int
Traceback (most recent call last):
SyntaxError: only single target (not list) can be annotated
&gt;&gt;&gt; (()): int
Traceback (most recent call last):
SyntaxError: only single target (not tuple) can be annotated
&gt;&gt;&gt; ([]): int
Traceback (most recent call last):
SyntaxError: only single target (not list) can be annotated

Corner-cases that used to fail to raise the correct error:

    &gt;&gt;&gt; def f(*, x=lambda __debug__:0): pass
    Traceback (most recent call last):
    SyntaxError: cannot assign to __debug__

    &gt;&gt;&gt; with (lambda *:0): pass
    Traceback (most recent call last):
    SyntaxError: named arguments must follow bare *

Corner-cases that used to crash:

    &gt;&gt;&gt; def f(**__debug__): pass
    Traceback (most recent call last):
    SyntaxError: cannot assign to __debug__

    &gt;&gt;&gt; def f(*xx, __debug__): pass
    Traceback (most recent call last):
    SyntaxError: cannot assign to __debug__

    &gt;&gt;&gt; import ä £
    Traceback (most recent call last):
    SyntaxError: invalid character '£' (U+00A3)</p></div>
      </div>

      <div id="splitTables">
        <table class="children sortable" id="id9758">
  
  <tr class="class">
    
    <td>Class</td>
    <td><a href="Lib.test.test_syntax.SyntaxTestCase.html" class="code" data-type="Class">SyntaxTestCase</a></td>
    <td><span class="undocumented">No class1/20 methods documented</span></td>
  </tr><tr class="function">
    
    <td>Function</td>
    <td><a href="Lib.test.test_syntax.html#test_main" class="code" data-type="Function">test_main</a></td>
    <td><span class="undocumented">Undocumented</span></td>
  </tr>
</table>
        

          
      </div>

      <div id="childList">

        <div class="basefunction">
  
  <a name="Lib.test.test_syntax.test_main">
    
  </a>
  <a name="test_main">
    
  </a>
  <div class="functionHeader">
    
    def
    test_main():
    
  </div>
  <div class="docstring functionBody">
    
    
    <div class="undocumented">Undocumented</div>
  </div>
</div>

      </div>
      <address>
        <a href="index.html">API Documentation</a> for Python3.8, generated by <a href="https://github.com/twisted/pydoctor/">pydoctor</a> 20.7.1 at 2020-11-24 05:02:55.
      </address>

    </div>

    <script src="pydoctor.js" type="text/javascript"></script>

  </body>
</html>